### ISSUE TITLE
Use serial2 in production

### ISSUE THREAD

**Issue by josejachuf** [de-vri-es/serial2-rs#2]
Hi @de-vri-es 

I am working on an app that reads and writes in the serial port and iteract with a REST API. This is developed in Python with pyserial. For what I need this is enough, but since I recently started studying Rust, I would like to do it with serial2.

Is it serial2 mature enough to use it in production? 

If so, maybe change from Python to Rust. For now, that I have the delivery date soon I will go for Python and then change. 

Jose

**Comment by de-vri-es** [comment]
I believe it is. Of course, it is a relatively new library, so it has not received a lot of testing besides what I have done myself. I'm pretty sure that reading/writing and configuring basic settings are working properly though, which is normally sufficient for most applications.

Plus, I am normally very quick to respond to issues and releasing fixes. So if you do run into problems, I'd love to hear about them so they can be fixed asap :)

**Comment by josejachuf** [comment]
Tjanks. I will try then

**Comment by josejachuf** [comment]
I was trying it yesterday several hours working together with the REST API and it worked fine. This week or the next we are going to do longer tests, several days. I will keep you informed .

Jose

**Comment by de-vri-es** [comment]
Awesome, that is nice to hear :)
