### ISSUE TITLE
simultaneously transmission reception serial data

### ISSUE THREAD

**Issue by learncodingforweb** [de-vri-es/serial2-rs#20]
Hi,
    You have provided example for loopback using Arc, But if receiver is waiting for data. how will it transmit data at the same time. There should be provision for simultaneously transmission reception using try_clone(), where it should provide separate reader and writer. can be used independently. Please you update

**Comment by de-vri-es** [comment]
Hi!

You don't need to `clone()` or `try_clone()` or `split()` if you use the non-trait `read()` and `write()` functions. They take `&self`, not `&mut self`.

**Comment by learncodingforweb** [comment]
will it work simultaneously. if reader is waiting for input. can it transmit data at the same time?

**Comment by de-vri-es** [comment]
Yes :)

**Comment by learncodingforweb** [comment]
Thanks, then I am closing the issue as able to read and write simultaneously.
