### ISSUE TITLE
Set `IGNBRK` and `IGNPAR` for `termios.c_iflag`

### ISSUE THREAD

**Issue by Tnze** [de-vri-es/serial2-rs#23]
It's required to set both parity and break indicators to be ignored to enter the "real raw mode". Otherwise the tty would insert `\0`s in the received data when UART is overrun. Which causes problems.

We should add an API to ignore break indicators.

**Comment by de-vri-es** [comment]
Good point. For now I'll atleast make sure that [`Settings::set_raw()`](https://docs.rs/serial2/latest/serial2/struct.Settings.html#method.set_raw) set these flags.

Thanks for reporting it!

**Comment by de-vri-es** [comment]
Fixed in 0.2.17. Thanks!

For now, if someone actually wants to receive parity errors or break conditions in the data stream, they will have to use [`as_termios_mut()`](https://docs.rs/serial2/latest/serial2/struct.Settings.html#method.as_termios_mut).
