### ISSUE TITLE
`write` and `write_vectored` functions on Unix systems use `read_timeout_ms` instead of `write_timeout_ms`

### ISSUE THREAD

**Issue by Polprzewodnikowy** [de-vri-es/serial2-rs#26]
Code in question is here: https://github.com/de-vri-es/serial2-rs/blob/main/src/sys/unix/mod.rs#L222-L224

Looks like a copy-paste bug from `read` function, but I'd like to confirm if write functions should use `self.write_timeout_ms` value.

**Comment by de-vri-es** [comment]
Oops, this is definitely a copy-pasta bug. Do you want to send a PR to fix it, or shall I?

**Comment by Polprzewodnikowy** [comment]
I've made PR here: https://github.com/de-vri-es/serial2-rs/pull/28

**Comment by de-vri-es** [comment]
Released with `v0.2.20`. Thanks for reporting and fixing the issue!
