### ISSUE TITLE
Unable to connect to RS232R device

### ISSUE THREAD

**Issue by ocelotsloth** [de-vri-es/serial2-rs#30]
:wave: Hey I know this isn't _super_ helpful just yet. I plan on digging a bit deeper to try and find a fix or at least more information.

I've got a device (https://www.sciencecenter.net/hutech/Hinode-sg/index.htm) with an embedded RS232R chip. I'm able to talk to this device using the [go-serial](https://github.com/bugst/go-serial/) library by setting the RTS status bit low and waiting a second or so for the CTS flag to bet set.

In Go, that looks like this:

```go
import (
	"go.bug.st/serial"
	"log"
	"time"
)

func isDeviceReady(port serial.Port) bool {
	statusBits, err := port.GetModemStatusBits()
	if err != nil {
		log.Fatal(err)
	}
	return statusBits.CTS
}

func InitializeSerialPort(portName string) serial.Port {
	port, err := serial.Open(
		portName,
		&serial.Mode{
			BaudRate: 38400,
			InitialStatusBits: &serial.ModemOutputBits{
				RTS: false,
			},
		},
	)
	if err != nil {
		log.Fatal(err)
	}

	// Wait for the device to signal that it's ready to receive commands
	for !isDeviceReady(port) {
		time.Sleep(100 * time.Millisecond)
	}
	log.Println("Device ready, lets go!")
	return port
}
```

For a variety of reasons, I'm doing this in Rust though and am working on getting this to work with serial2. This is where I'm at so far (be nice :sweat_smile:, I'm just starting with Rust and trying to get a minimally viable something together first):

```rust
    fn connect(&mut self) {
        godot_print!("Connecting to: {}", self.port.as_str());
        let serial_port = SerialPort::open(self.port.as_str(), |mut settings: Settings| {
            settings.set_raw();
            settings.set_baud_rate(self.baud_rate)?;
            // note: I've tried a variety of settings, from only baud rate to this
            settings.set_flow_control(FlowControl::RtsCts);
            Ok(settings)
        })
        .expect("Failed to open port");
        thread::sleep(time::Duration::from_millis(200));
        // Here just as a sanity check I've tried setting this true and false, with the same results
        serial_port.set_rts(false).expect("Failed to set RTS low");
        self.serial_port = Some(serial_port);
    }
```

It seems like the RTS bit is not actually being set with serial2--where it works and I can send/receive with the Go library. Actually, even without sending or receiving data it's clear because this device shuts off after connecting to the serial port. Only after setting RTS low will it turn back on while connected.

Looking at differences, I can see that the Go library is setting those flags a bit differently--using `TIOCMSET` to set the entire register instead of `TIOCMBIS`/`TIOCMBIC` to flip individual flags:

https://github.com/bugst/go-serial/blob/0925f99089e0b2f8324e7de73fd40fbfd5ddd255/serial_unix.go#L180-L191
```go
func (port *unixPort) SetRTS(rts bool) error {
	status, err := port.getModemBitsStatus()
	if err != nil {
		return err
	}
	if rts {
		status |= unix.TIOCM_RTS
	} else {
		status &^= unix.TIOCM_RTS
	}
	return port.setModemBitsStatus(status)
}
```

Vs serial2:

https://github.com/de-vri-es/serial2-rs/blob/cbb18cf4146267c1c7b6509d42fa77775b1485d1/src/sys/unix/mod.rs#L314-L323

---

There may be something else but this is the difference I've seen so far.

Tomorrow I'm going to try implementing the same `TIOCMSET` behavior in serial2 and just checking if, for some reason, this specific chip/device behaves differently then I would expect. I'll share those findings when I get them.

**Comment by de-vri-es** [comment]
Thanks for the detailed report! Let me know what you find.

Note that maybe with RTS/CTS flow control enabled, it could be that manually setting the RTS bit won't work. Maybe you need to perform a regular `write()` to set it.

Does the go library enable RTS/CTS flow control?

**Comment by ocelotsloth** [comment]
Alright so I was able to track this down. I think that that go library is setting some different defaults for the DTR line.

This device actually requires setting the DTR line, and waiting for the CTS in response.
