### ISSUE TITLE
I need an algorithm to calculate how long write() takes.

### ISSUE THREAD

**Issue by wc7086** [de-vri-es/serial2-rs#35]
~~I have not tested this further, and so far have found that even sending two bytes of data in a row has a very high chance of losing the second byte.~~

I've found that at high enough baud rates, it only takes a theoretical value of one bit (1s / rate) to send a byte (write()), whereas at very low baud rates (e.g. 9600 bps), the theoretical value doesn't take enough time to complete a byte.

**Comment by wc7086** [comment]
My current solution is to add a 50 microsecond delay after each write.

**Comment by wc7086** [comment]
I have found that this is baud rate related, and when I use the 460800 baud rate, I don't need to add this delay.

**Comment by de-vri-es** [comment]
You may run into the problem that to transfer one byte, you have to transfer more than one bit: there's also the start condition, optional parity bit and the stop bit(s). You have to take those into account too.

But then there's also potential scheduling overhead in the kernel. And if you sleep in your own process, you also don't have any guarantee about the *exact* length of your sleep.

What is your end goal exactly? Do you want to calculate a good value for a read/write timeout?

**Comment by wc7086** [comment]
> What is your end goal exactly? Do you want to calculate a good value for a read/write timeout?

I need to transfer data continuously, so I want to calculate the time between each wire() interval at the current baud rate to ensure that data is not overwritten.

After numerous attempts, I gave up. With a baud rate of approximately 500,000 bps, only a few microseconds of delay are required. According to the theoretical calculation of 1s / rate * 10, the system scheduling overhead at this time is only a few microseconds, and the differences between systems should be significant. Therefore, calculating the required time is impossible.
