### ISSUE TITLE
setting configuration does NOT work

### ISSUE THREAD

**Issue by Sieyalixnet** [de-vri-es/serial2-rs#5]
Environment: apple M2 and rust edition = "2021".

I used many method to set the Settings including implement the `apply_to_settings` trait, get the `Settings` from a port and then modify it by using like `set_char_size` and then apply it  by `set_configuration`.
And then I use `get_configuration` to check it, but the settings do not change even I used `set_configuration` to modified it.
I modify most of settings like baud rate, char size and stop bits..., but it ONLY works when I was modifying the baud rate. It do not throw an exception when I use `set_configuration`.

**Comment by de-vri-es** [comment]
Could you tell me a bit more? Which serial port device are you trying to change the settings for? What is the name of the device on the system, and what is the name according to the vendor?

**Comment by de-vri-es** [comment]
And could you share a minimum example showing that the settings are not updated as expected without raising an error?

**Comment by Sieyalixnet** [comment]
I am sorry, here's the code

```
fn main() {
    let mut port = SerialPort::open("/dev/cu.usbserial-0001", 115200).unwrap();
    let mut settings1 = port.get_configuration().unwrap().clone();
    println!(
        "{:?},{:?},{:?},{:?},{:?}",
        settings1.get_char_size(),
        settings1.get_flow_control(),
        settings1.get_parity(),
        settings1.get_stop_bits(),
        settings1.get_baud_rate()
    );
    settings1.set_baud_rate(9600);
    settings1.set_char_size(serial2::CharSize::Bits5);
    settings1.set_flow_control(serial2::FlowControl::XonXoff);
    port.set_configuration(&settings1);
    let mut settings2 = port.get_configuration().unwrap().clone();
    println!(
        "{:?},{:?},{:?},{:?},{:?}",
        settings2.get_char_size(),
        settings2.get_flow_control(),
        settings2.get_parity(),
        settings2.get_stop_bits(),
        settings2.get_baud_rate()
    );
}
```

in terminal, the output is

```
Ok(Bits8),Ok(None),Ok(None),Ok(One),Ok(115200)
Ok(Bits8),Ok(None),Ok(None),Ok(One),Ok(9600)
```

I changed the library to serialport, but it works.

**Comment by de-vri-es** [comment]
Hmm, you're not checking for errors when setting the configuration.

Could you try that to see if it reports an error?

```rust
 port.set_configuration(&settings1).unwrap();
```

**Comment by Sieyalixnet** [comment]
If I set "serial2::FlowControl::RtsCts" for flow control, it will crash. So here I try to set other settings.

However it will success, but still perform like above:

`fn main() {
    let mut port = SerialPort::open("/dev/cu.Bluetooth-Incoming-Port", 115200).unwrap();
    let mut settings1 = port.get_configuration().unwrap().clone();
    println!(
        "{:?},{:?},{:?},{:?},{:?}",
        settings1.get_char_size(),
        settings1.get_flow_control(),
        settings1.get_parity(),
        settings1.get_stop_bits(),
        settings1.get_baud_rate()
    );
    settings1.set_baud_rate(9600).unwrap();
    settings1.set_char_size(serial2::CharSize::Bits5);
    settings1.set_parity(serial2::Parity::Even);
    settings1.set_stop_bits(serial2::StopBits::Two);
    //settings1.set_flow_control(serial2::FlowControl::RtsCts);
    port.set_configuration(&settings1).unwrap();//!!!! I added unwrap() here
    let mut settings2 = port.get_configuration().unwrap().clone();
    println!(
        "{:?},{:?},{:?},{:?},{:?}",
        settings2.get_char_size(),
        settings2.get_flow_control(),
        settings2.get_parity(),
        settings2.get_stop_bits(),
        settings2.get_baud_rate()
    );
}
`

In terminal :
`Ok(Bits8),Ok(None),Ok(None),Ok(One),Ok(115200)
Ok(Bits8),Ok(None),Ok(None),Ok(Two),Ok(9600)`

Even i added unwrap, it was successful to set the configuration. but the char size and parity didn't change.

**Comment by DanielJoyce** [comment]
Not all hardware is required to support all formats. It may be baudot code is not supported, its super old and very little used.

If its not supported though, I'd expect the set_configuration to return an error.?

**Comment by DanielJoyce** [comment]
Looking, it appears set_on_file uses an ioctl on linux instead of tcsetattr

Also it says it allows the buffer to drain before applying settings.

**Comment by DanielJoyce** [comment]
From here:

https://manpages.debian.org/testing/manpages-dev/ioctl_tty.2.en.html


<p class="Pp" style="min-height: 1em; padding-left: 1em; color: rgb(0, 0, 0); font-family: Inconsolata, monospace; font-size: 16.64px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: 0.15px; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">The following four ioctls, added in Linux 2.6.20, are just like<span> </span><b>TCGETS</b>,<span> </span><b>TCSETS</b>,<span> </span><b>TCSETSW</b>,<span> </span><b>TCSETSF</b>, except that they take a<span> </span><i>struct termios2 *</i><span> </span>instead of a<span> </span><i>struct termios *</i>. If the structure member<span> </span><b>c_cflag</b><span> </span>contains the flag<span> </span><b>BOTHER</b>, then the baud rate is stored in the structure members<span> </span><b>c_ispeed</b><span> </span>and<span> </span><b>c_ospeed</b><span> </span>as integer values. These ioctls are not supported on all architectures.</p><div class="Bd-indent" style="margin-left: 3.8em; color: rgb(0, 0, 0); font-family: Inconsolata, monospace; font-size: 16.64px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: 0.15px; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">

TCGETS2 | struct termios2 *argp
-- | --
TCSETS2 | const struct termios2 *argp
TCSETSW2 | const struct termios2 *argp
TCSETSF2 | const struct termios2 *argp

</div>

Are we using a termios2 struct for tcsetsw2?

**Comment by DanielJoyce** [comment]
Okay, it looks like termios2 is being used.

**Comment by de-vri-es** [comment]
Yeah, but this issue is about macOS, so it's somewhat different.

One annoying thing: the underlying syscall for setting TTY settings reports success if it applied *any* of the settings, not if it applied *all* of the settings.

**Comment by de-vri-es** [comment]
I don't have a macOS device, so I can't really debug this myself.

What would help is to try and set each setting one at a time, and see if we get a failure then:

```rust
fn main() {
    let mut port = SerialPort::open("/dev/cu.Bluetooth-Incoming-Port", 115200).unwrap();
    let mut settings = port.get_configuration().unwrap();
    print_settings(&settings);
    
    settings.set_baud_rate(9600).unwrap();
    port.set_configuration(&settings).unwrap();
    let mut setting = port.get_configuration().unwrap();
    print_settings(&settings);

    settings.set_char_size(serial2::CharSize::Bits5);
    port.set_configuration(&settings).unwrap();
    let mut setting = port.get_configuration().unwrap();
    print_settings(&settings);

    settings.set_parity(serial2::Parity::Even);
    port.set_configuration(&settings).unwrap();
    let mut setting = port.get_configuration().unwrap();
    print_settings(&settings);

    settings.set_stop_bits(serial2::StopBits::Two);
    port.set_configuration(&settings).unwrap();
    let mut setting = port.get_configuration().unwrap();
    print_settings(&settings);

    // settings1.set_flow_control(serial2::FlowControl::RtsCts);
    // port.set_configuration(&settings).unwrap();
    // let mut setting = port.get_configuration().unwrap();
}

fn print_settings(settings: &serial2::Settings) {
    println!(
        "{:?},{:?},{:?},{:?},{:?}",
        settings.get_char_size(),
        settings.get_flow_control(),
        settings.get_parity(),
        settings.get_stop_bits(),
        settings.get_baud_rate()
    );
}
```

**Comment by Sieyalixnet** [comment]
Setting flow control to  RtsCts will be crashed, but it is ok if I set XonXoff. So I add this setting. Here's the code:

```rust
use serial2::SerialPort;

fn main() {
    let mut port = SerialPort::open("/dev/cu.usbserial-110", 115200).unwrap();
    let mut settings = port.get_configuration().unwrap();
    print_settings(&settings);

    settings.set_baud_rate(9600).unwrap();
    port.set_configuration(&settings).unwrap();
    let mut setting = port.get_configuration().unwrap();
    print_settings(&settings);

    settings.set_char_size(serial2::CharSize::Bits5);
    port.set_configuration(&settings).unwrap();
    let mut setting = port.get_configuration().unwrap();
    print_settings(&settings);

    settings.set_parity(serial2::Parity::Even);
    port.set_configuration(&settings).unwrap();
    let mut setting = port.get_configuration().unwrap();
    print_settings(&settings);

    settings.set_stop_bits(serial2::StopBits::Two);
    port.set_configuration(&settings).unwrap();
    let mut setting = port.get_configuration().unwrap();
    print_settings(&settings);

    settings.set_flow_control(serial2::FlowControl::XonXoff);
    port.set_configuration(&settings).unwrap();
    let mut setting = port.get_configuration().unwrap();
}

fn print_settings(settings: &serial2::Settings) {
    println!(
        "{:?},{:?},{:?},{:?},{:?}",
        settings.get_char_size(),
        settings.get_flow_control(),
        settings.get_parity(),
        settings.get_stop_bits(),
        settings.get_baud_rate()
    );
}
```

Here's the output:

```shell
Ok(Bits8),Ok(None),Ok(None),Ok(One),Ok(115200)
Ok(Bits8),Ok(None),Ok(None),Ok(One),Ok(9600)
Ok(Bits5),Ok(None),Ok(None),Ok(One),Ok(9600)
Ok(Bits5),Ok(None),Ok(Odd),Ok(One),Ok(9600)
Ok(Bits5),Ok(None),Ok(Odd),Ok(Two),Ok(9600)
```

It is quite strange in setting the flow control and parity.

**Comment by Sieyalixnet** [comment]
Yes, the flow control can not be set maybe caused by the hardware. I try to set flow control by another library named serialport, it also doesn't work.(But in that library, both of them (FlowControl::Hardware, FlowControl::Software) can not be set.)
